server:
  port: 8081

spring:
  # datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/person?useSSL=false&serverTimezone=UTC
    username: root
    password: admin@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      max-lifetime: 2000
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataCP
      connection-timeout: 30000

mybatis:
  check-config-location: true
  #xml配置方式
  config-location: classpath:mybatis-config.xml

  #yml文件配置方式
  #mapper-locations: classpath:mappers/*.xml
  #type-aliases-package: top.xx.xxx

