spring:
  # redis configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    client-name: redis
    timeout: 1000
    # springboot2.0-redis
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        max-wait: 10ms
